name: Sync from Club Repo

on:
  schedule:
    - cron: "0 9 * * 0"   # every Sunday at 9:00 UTC = 4:00 AM EST
  workflow_dispatch:

permissions:
  contents: write   # allow pushing into your repo

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Clone club repo
        run: |
          git clone https://github.com/codingUnited/challenge-EddieRichardson.git source
          cd source

          # Push each branch individually (excluding workflow)
          for branch in $(git for-each-ref --format='%(refname:short)' refs/heads/); do
            if [ "$branch" != "workflow" ]; then
              git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Eddie-Richardson/challenge-EddieRichardson.git $branch
            fi
          done

          # Push all tags
          git push --tags --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Eddie-Richardson/challenge-EddieRichardson.git
